services:
  mongodb-social:
    image: mongo:latest
    container_name: mongodb-social
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-codelsoft
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

